  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1054 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527 in _call_impl
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518 in _wrapped_call_impl
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1169 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/peft/tuners/tuners_utils.py", line 107 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527 in _call_impl
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518 in _wrapped_call_impl
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/peft/peft_model.py", line 1003 in forward
  File "/home/seongyoon/jupyter/FedBiscuit/federatedscope/llm/model/adapter_builder.py", line 251 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16 in decorate_autocast
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 806 in __call__
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/utils/operations.py", line 818 in forward
  ...
[E ProcessGroupGloo.cpp:2810] [Rank 0]: Rank 1 failed to pass monitoredBarrier in 1800000 ms
[E ProcessGroupGloo.cpp:138] [Rank 0]: Ranks 1 failed to pass monitoredBarrier in 1800000 ms
Traceback (most recent call last):
  File "/home/seongyoon/jupyter/FedBiscuit/federatedscope/main.py", line 98, in <module>
    _ = runner.run()
  File "/home/seongyoon/jupyter/FedBiscuit/federatedscope/core/fed_runner.py", line 435, in run
    self._run_simulation()
  File "/home/seongyoon/jupyter/FedBiscuit/federatedscope/core/fed_runner.py", line 561, in _run_simulation
    self._handle_msg(msg) #클라이언트의 핸들러로 바로 처리하면서 비워낸다.
  File "/home/seongyoon/jupyter/FedBiscuit/federatedscope/core/fed_runner.py", line 466, in _handle_msg
    self.client[each_receiver].msg_handlers[msg.msg_type](msg)
  File "/home/seongyoon/jupyter/FedBiscuit/federatedscope/llm/llm_local/client.py", line 429, in callback_funcs_for_adapter_eval
    self.trainer.update(
  File "/home/seongyoon/jupyter/FedBiscuit/federatedscope/core/trainers/torch_trainer.py", line 153, in update
    barrier_all()
  File "/home/seongyoon/jupyter/FedBiscuit/federatedscope/llm/utils_dist.py", line 8, in barrier_all
    dist.barrier()
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 3696, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: ProcessGroupWrapper: Monitored Barrier encountered error running collective: CollectiveFingerPrint(SequenceNumber=135817OpType=BARRIER). Error: 
[../third_party/gloo/gloo/transport/tcp/pair.cc:525] Read error [143.248.157.69]:61608: Connection reset by peer
Exception raised from runCollectiveChecks at ../torch/csrc/distributed/c10d/ProcessGroupWrapper.cpp:576 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7fef3f9a5617 in /home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7fef3f96098d in /home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x15ba06d (0x7fef25dba06d in /home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #3: c10d::ProcessGroupWrapper::barrier(c10d::BarrierOptions const&) + 0x42 (0x7fef29ecb2d2 in /home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x567a342 (0x7fef29e7a342 in /home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x5684960 (0x7fef29e84960 in /home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x5684a65 (0x7fef29e84a65 in /home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x4cb046b (0x7fef294b046b in /home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x4cae44c (0x7fef294ae44c in /home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x1a039d8 (0x7fef262039d8 in /home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x568df24 (0x7fef29e8df24 in /home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x568ee8d (0x7fef29e8ee8d in /home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0xc48fb8 (0x7fef3cc48fb8 in /home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #13: <unknown function> + 0x3f727f (0x7fef3c3f727f in /home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #14: /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9() [0x507107]
frame #15: _PyObject_MakeTpCall + 0x2ec (0x4f03bc in /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9)
frame #16: /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9() [0x505020]
frame #17: _PyEval_EvalFrameDefault + 0x1237 (0x4e8867 in /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9)
frame #18: /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9() [0x4f7e03]
frame #19: _PyEval_EvalFrameDefault + 0x2f6b (0x4ea59b in /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9)
frame #20: /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9() [0x4e672a]
frame #21: _PyFunction_Vectorcall + 0xd5 (0x4f7b25 in /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9)
frame #22: _PyEval_EvalFrameDefault + 0x4d54 (0x4ec384 in /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9)
frame #23: /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9() [0x4f7e03]
frame #24: _PyEval_EvalFrameDefault + 0x3cf (0x4e79ff in /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9)
frame #25: /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9() [0x4e672a]
frame #26: /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9() [0x504e0d]
frame #27: _PyEval_EvalFrameDefault + 0x1237 (0x4e8867 in /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9)
frame #28: /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9() [0x4f7e03]
frame #29: /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9() [0x504d01]
frame #30: _PyEval_EvalFrameDefault + 0x3cf (0x4e79ff in /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9)
frame #31: /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9() [0x4e672a]
frame #32: _PyFunction_Vectorcall + 0xd5 (0x4f7b25 in /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9)
frame #33: _PyEval_EvalFrameDefault + 0x68a (0x4e7cba in /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9)
frame #34: /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9() [0x4f7e03]
frame #35: _PyEval_EvalFrameDefault + 0x68a (0x4e7cba in /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9)
frame #36: /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9() [0x4f7e03]
frame #37: _PyEval_EvalFrameDefault + 0x68a (0x4e7cba in /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9)
frame #38: /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9() [0x4e672a]
frame #39: _PyEval_EvalCodeWithName + 0x47 (0x4e63b7 in /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9)
frame #40: PyEval_EvalCodeEx + 0x39 (0x4e6369 in /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9)
frame #41: PyEval_EvalCode + 0x1b (0x59363b in /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9)
frame #42: /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9() [0x5c0ee7]
frame #43: /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9() [0x5bcef0]
frame #44: /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9() [0x456252]
frame #45: PyRun_SimpleFileExFlags + 0x1a2 (0x5b6bf2 in /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9)
frame #46: Py_RunMain + 0x37e (0x5b40ee in /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9)
frame #47: Py_BytesMain + 0x39 (0x5876f9 in /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9)
frame #48: <unknown function> + 0x29d90 (0x7fef69429d90 in /lib/x86_64-linux-gnu/libc.so.6)
frame #49: __libc_start_main + 0x80 (0x7fef69429e40 in /lib/x86_64-linux-gnu/libc.so.6)
frame #50: /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9() [0x5875ae]

[2025-08-31 10:22:33,637] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 3565058 closing signal SIGTERM
[2025-08-31 10:22:33,638] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 3565060 closing signal SIGTERM
[2025-08-31 10:22:33,639] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 3565061 closing signal SIGTERM
[2025-08-31 10:22:36,423] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -11) local_rank: 1 (pid: 3565059) of binary: /home/seongyoon/anaconda3/envs/fs-llm/bin/python3.9
Traceback (most recent call last):
  File "/home/seongyoon/anaconda3/envs/fs-llm/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/seongyoon/anaconda3/envs/fs-llm/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=========================================================
federatedscope/main.py FAILED
---------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
---------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-08-31_10:22:33
  host      : wave5.kaist.ac.kr
  rank      : 1 (local_rank: 1)
  exitcode  : -11 (pid: 3565059)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 3565059
=========================================================
